packages:
  - apps/*
  - packages/*

linkWorkspacePackages: true
networkConcurrency: 16

catalog:
  react: 19.2.8
  react-dom: 19.2.8
  react-email: 6.9.3
  next: 16.3.4
  next-intl: 4.14.2
  better-auth: 1.7.3
  typescript: 7.0.2
  "@types/node": 26.4.1
  "@types/react": 19.2.18
  "@types/react-dom": 19.2.7

hoistPattern:
  - typescript
  - react
  - drizzle-orm
  - pg

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - "@turbo/darwin-64@2.10.12"
  - "@turbo/darwin-arm64@2.10.12"
  - "@turbo/linux-64@2.10.12"
  - "@turbo/linux-arm64@2.10.12"
  - "@turbo/windows-64@2.10.12"
  - "@turbo/windows-arm64@2.10.12"
  - turbo@2.10.12
