import { z } from "zod";

export const situationCatalog = {
  unauthenticated: {
    code: "UNAUTHORIZED",
    status: 401,
    reason: "SESSION_REQUIRED",
    message: "Your session is missing or has expired. Sign in to continue.",
  },
  invalidCredentials: {
    code: "UNAUTHORIZED",
    status: 401,
    reason: "INVALID_CREDENTIALS",
    message: "Incorrect email or password.",
  },
  selectOrganization: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "ACTIVE_ORGANIZATION_REQUIRED",
    message: "Select an active Organization before accessing Cost Tracker data.",
  },
  notMember: {
    code: "FORBIDDEN",
    status: 403,
    reason: "ORGANIZATION_MEMBERSHIP_REQUIRED",
    message: "Membership in the active Organization is required.",
  },
  incompleteProfile: {
    code: "UNPROCESSABLE_CONTENT",
    status: 422,
    reason: "PARTICIPANT_PROFILE_REQUIRED",
    message: "Complete your Participant profile before accessing Projects.",
  },
  agreementRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PARTICIPANT_AGREEMENT_REQUIRED",
    message:
      "Accept the current Participant agreement before accessing Projects.",
  },
  verifyEmail: {
    code: "FORBIDDEN",
    status: 403,
    reason: "EMAIL_VERIFICATION_REQUIRED",
    message: "Verify your email before continuing.",
  },
  hostCoordinationRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "HOST_COORDINATION_REQUIRED",
    message:
      "You need Hosting Organization staff access or an assignment to this Project.",
  },
  projectNotFound: {
    code: "NOT_FOUND",
    status: 404,
    reason: "PROJECT_NOT_FOUND",
    message: "Project not found in scope.",
  },
  partnershipNotFound: {
    code: "NOT_FOUND",
    status: 404,
    reason: "PROJECT_PARTNERSHIP_NOT_FOUND",
    message: "Project Partnership not found in scope.",
  },
  organizationManagementRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "ORGANIZATION_MANAGEMENT_REQUIRED",
    message:
      "You need Organization Owner or Admin access to manage this Organization.",
  },
  partnerCoordinationRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PARTNER_COORDINATION_REQUIRED",
    message:
      "You need Partner Organization staff access or an assignment to this Project Partnership.",
  },
  coordinatorSelectionRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "ELIGIBLE_COORDINATOR_REQUIRED",
    message:
      "Select an Owner, Admin, or Project Coordinator in the Partner Organization.",
  },
  invalidProjectCursor: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "INVALID_PROJECT_CURSOR",
    message: "The Project page cursor is invalid for these filters.",
  },
  projectReadRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PROJECT_READ_REQUIRED",
    message: "The active Organization role cannot read this Project.",
  },
  hostingStaffRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "HOSTING_STAFF_REQUIRED",
    message:
      "You need Hosting Organization Owner, Admin, or Project Coordinator access.",
  },
  hostingSideRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "HOSTING_SIDE_REQUIRED",
    message: "Only the Hosting Organization can assign this Project.",
  },
  selfPartnership: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "SELF_PARTNERSHIP",
    message: "The Hosting Organization cannot be its own Partner Organization.",
  },
  partnerOrganizationNotFound: {
    code: "NOT_FOUND",
    status: 404,
    reason: "PARTNER_ORGANIZATION_NOT_FOUND",
    message: "Partner Organization not found.",
  },
  partnershipAlreadyAssigned: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTNERSHIP_ALREADY_ASSIGNED",
    message: "This Organization is already assigned to the Project.",
  },
  partnershipInvariant: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTNERSHIP_INVARIANT",
    message:
      "This Project Partnership cannot be created with the selected Organizations.",
  },
  partnershipReferenced: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTNERSHIP_REFERENCED",
    message:
      "Remove or reassign represented Project Participations before removing this Project Partnership.",
  },
  projectAlreadyCompleted: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PROJECT_ALREADY_COMPLETED",
    message: "Project is already completed.",
  },
  setupLinkNotFound: {
    code: "NOT_FOUND",
    status: 404,
    reason: "SETUP_LINK_NOT_FOUND",
    message: "Setup link not found.",
  },
  setupLinkWrongEmail: {
    code: "FORBIDDEN",
    status: 403,
    reason: "SETUP_LINK_WRONG_EMAIL",
    message: "This setup link belongs to another email address.",
  },
  setupLinkDisabled: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "SETUP_LINK_DISABLED",
    message: "This setup link is disabled.",
  },
  setupLinkExpired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "SETUP_LINK_EXPIRED",
    message: "This setup link has expired.",
  },
  organizationOwnerRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "ORGANIZATION_OWNER_REQUIRED",
    message: "You must be an Owner of the selected Organization.",
  },
  setupLinkUsed: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "SETUP_LINK_USED",
    message: "This setup link has already been used.",
  },
  staffInvitationRoleTooHigh: {
    code: "FORBIDDEN",
    status: 403,
    reason: "STAFF_INVITATION_ROLE_TOO_HIGH",
    message: "This invitation would grant a role above your own.",
  },
  staffInvitationNotFound: {
    code: "NOT_FOUND",
    status: 404,
    reason: "STAFF_INVITATION_NOT_FOUND",
    message: "Organization Invitation not found.",
  },
  staffInvitationWrongKind: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "STAFF_INVITATION_WRONG_KIND",
    message: "This invitation is not an Organization staff invitation.",
  },
  staffInvitationClosed: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "STAFF_INVITATION_CLOSED",
    message: "Organization Invitation is no longer pending.",
  },
  staffInvitationExpired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "STAFF_INVITATION_EXPIRED",
    message: "Organization Invitation has expired.",
  },
  staffInvitationWrongEmail: {
    code: "FORBIDDEN",
    status: 403,
    reason: "STAFF_INVITATION_WRONG_EMAIL",
    message: "Sign in with the invited email address.",
  },
  invalidOrganizationRole: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "INVALID_ORGANIZATION_ROLE",
    message:
      'The "member" role is forbidden in Cost Tracker. Use a defined Organization role.',
  },
  registrationLinkNotFound: {
    code: "NOT_FOUND",
    status: 404,
    reason: "REGISTRATION_LINK_NOT_FOUND",
    message: "Registration link not found.",
  },
  registrationLinkClosed: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "REGISTRATION_LINK_CLOSED",
    message: "Registration link is closed.",
  },
  participantInvitationNotFound: {
    code: "NOT_FOUND",
    status: 404,
    reason: "PARTICIPANT_INVITATION_NOT_FOUND",
    message: "Participant Invitation not found.",
  },
  participantInvitationWrongAccount: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PARTICIPANT_INVITATION_WRONG_ACCOUNT",
    message: "Invitation is not for this account.",
  },
  participantInvitationClosed: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTICIPANT_INVITATION_CLOSED",
    message: "Invitation is closed.",
  },
  participantInvitationExpired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTICIPANT_INVITATION_EXPIRED",
    message: "Participant Invitation has expired.",
  },
  participantAlreadyParticipates: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTICIPANT_ALREADY_PARTICIPATES",
    message: "This person already participates in this Project.",
  },
  participantAlreadyInvited: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTICIPANT_ALREADY_INVITED",
    message: "This person already has an invitation to this Project.",
  },
  joinedOtherPartner: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "JOINED_OTHER_PARTNER",
    message:
      "You already joined this Project through another Partner Organization.",
  },
  membershipChanged: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "MEMBERSHIP_CHANGED",
    message: "Membership changed; please retry onboarding.",
  },
  participationIdentityConflict: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTICIPATION_IDENTITY_CONFLICT",
    message: "This identity already participates in this Project.",
  },
  participantInvitationAccepted: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTICIPANT_INVITATION_ACCEPTED",
    message: "Accepted invitations cannot be changed.",
  },
  registrationClaimLocked: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "REGISTRATION_CLAIM_LOCKED",
    message: "A non-editable Claim prevents reopening registration.",
  },
  agreementUnavailable: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTICIPANT_AGREEMENT_UNAVAILABLE",
    message: "Participant agreement is not yet available.",
  },
  partnerClaimEditRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PARTNER_CLAIM_EDIT_REQUIRED",
    message: "Only the Partner Organization may edit its Claim.",
  },
  payoutSelectionLocked: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PAYOUT_SELECTION_LOCKED",
    message:
      "Payout Account selection is locked while the Claim is not editable.",
  },
  partnerPayoutSelectionRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTNER_PAYOUT_SELECTION_REQUIRED",
    message: "Select a Payout Account belonging to the Partner Organization.",
  },
  payoutAccountRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PAYOUT_ACCOUNT_REQUIRED",
    message: "Select a Partner Payout Account before saving the Claim.",
  },
  claimNotEditable: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "CLAIM_NOT_EDITABLE",
    message: "Claim is not editable.",
  },
  claimRequiredForCosts: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "CLAIM_REQUIRED_FOR_COSTS",
    message: "Save an editable Claim before adding costs.",
  },
  partnerCostsRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PARTNER_COSTS_REQUIRED",
    message: "Only the Partner Organization may manage Claim costs.",
  },
  allocationParticipationRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "ALLOCATION_PARTICIPATION_REQUIRED",
    message:
      "Each allocation must reference a Participation in this Project Partnership.",
  },
  costEntryRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "COST_ENTRY_REQUIRED",
    message: "Cost entry does not belong to this Claim.",
  },
  claimDocumentReferencesRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "CLAIM_DOCUMENT_REFERENCES_REQUIRED",
    message: "Cost entry and Proof Document must belong to this Claim.",
  },
  partnerJourneysRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PARTNER_JOURNEYS_REQUIRED",
    message: "Only the Partner Organization may manage Participant Journeys.",
  },
  journeysLocked: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "JOURNEYS_LOCKED",
    message: "Claim is locked; Participant Journeys cannot change.",
  },
  participationSelectionRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTICIPATION_SELECTION_REQUIRED",
    message: "Select a Participation in this Project Partnership.",
  },
  journeyAlreadyExists: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "JOURNEY_ALREADY_EXISTS",
    message: "This Participation already has a Participant Journey.",
  },
  claimRequiredForJourney: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "CLAIM_REQUIRED_FOR_JOURNEY",
    message: "Save an editable Claim before updating a Participant Journey.",
  },
  journeySelectionRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "JOURNEY_SELECTION_REQUIRED",
    message:
      "Select an existing Participant Journey in this Project Partnership.",
  },
  partnerOnboardingProgressRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PARTNER_ONBOARDING_PROGRESS_REQUIRED",
    message:
      "Only the Partner Organization may read Participant onboarding progress.",
  },
  partnerParticipantSearchRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PARTNER_PARTICIPANT_SEARCH_REQUIRED",
    message: "Only the Partner Organization may search onboarded Participants.",
  },
  partnerParticipationCreateRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PARTNER_PARTICIPATION_CREATE_REQUIRED",
    message: "Only the Partner Organization may create its Participation.",
  },
  participationCreateLocked: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTICIPATION_CREATE_LOCKED",
    message: "Locked Claim prevents Participation creation.",
  },
  eligibleParticipantRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "ELIGIBLE_PARTICIPANT_REQUIRED",
    message: "Select an eligible onboarded User or use a Participant invitation.",
  },
  participationDuplicate: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTICIPATION_DUPLICATE",
    message:
      "Identity already participates in this Project; request merge review.",
  },
  participationRepresentationConflict: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTICIPATION_REPRESENTATION_CONFLICT",
    message: "Participation cannot be created for this Project Partnership.",
  },
  partnerParticipationUpdateRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PARTNER_PARTICIPATION_UPDATE_REQUIRED",
    message: "Only the Partner Organization may update its Participation.",
  },
  participationUpdateLocked: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTICIPATION_UPDATE_LOCKED",
    message: "Locked Claim prevents Participation changes.",
  },
  participationNotFound: {
    code: "NOT_FOUND",
    status: 404,
    reason: "PARTICIPATION_NOT_FOUND",
    message: "Participation not found in scope.",
  },
  partnerParticipationRemoveRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PARTNER_PARTICIPATION_REMOVE_REQUIRED",
    message: "Only the Partner Organization may remove its Participation.",
  },
  participationRemoveLocked: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTICIPATION_REMOVE_LOCKED",
    message: "Locked Claim prevents Participation removal.",
  },
  participationJourneyOrCostReferenced: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTICIPATION_JOURNEY_OR_COST_REFERENCED",
    message:
      "Participation is referenced by a Participant Journey or Cost Allocation; request review instead.",
  },
  participationReferenced: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PARTICIPATION_REFERENCED",
    message: "Participation is referenced; request review instead.",
  },
  partnerDuplicateReviewRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PARTNER_DUPLICATE_REVIEW_REQUIRED",
    message: "Only the Partner Organization may review duplicate identities.",
  },
  reviewTaskNotFound: {
    code: "NOT_FOUND",
    status: 404,
    reason: "REVIEW_TASK_NOT_FOUND",
    message: "Review Task not found in scope.",
  },
  reviewTaskNotOpen: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "REVIEW_TASK_NOT_OPEN",
    message: "Review Task is not open.",
  },
  reviewTaskNotAssigned: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "REVIEW_TASK_NOT_ASSIGNED",
    message: "Review Task must be assigned before resolution.",
  },
  reviewTaskAssigneeRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "REVIEW_TASK_ASSIGNEE_REQUIRED",
    message: "Only the assigned reviewer may resolve this Review Task.",
  },
  reviewTaskSurvivorRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "REVIEW_TASK_SURVIVOR_REQUIRED",
    message: "Review Task cannot be resolved with this survivor.",
  },
  partnerClaimPreviewRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PARTNER_CLAIM_PREVIEW_REQUIRED",
    message: "Only the Partner Organization may preview its Claim.",
  },
  partnerClaimSubmitRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PARTNER_CLAIM_SUBMIT_REQUIRED",
    message: "Only the Partner Organization may submit its Claim.",
  },
  claimRequiredForSubmission: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "CLAIM_REQUIRED_FOR_SUBMISSION",
    message: "Save an editable Claim before submitting.",
  },
  reviewReasonRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "REVIEW_REASON_REQUIRED",
    message: "A review reason is required.",
  },
  hostingClaimReviewRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "HOSTING_CLAIM_REVIEW_REQUIRED",
    message: "Only Hosting staff may review Claims.",
  },
  claimNotFound: {
    code: "NOT_FOUND",
    status: 404,
    reason: "CLAIM_NOT_FOUND",
    message: "Claim not found in scope.",
  },
  claimSubmittedRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "CLAIM_SUBMITTED_REQUIRED",
    message: "Claim must be submitted for this review decision.",
  },
  claimRejectedRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "CLAIM_REJECTED_REQUIRED",
    message: "Claim must be rejected for this review decision.",
  },
  claimReviewUnavailable: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "CLAIM_REVIEW_UNAVAILABLE",
    message: "No submitted Claim is available for review.",
  },
  hostingPaymentRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "HOSTING_PAYMENT_REQUIRED",
    message: "Only Hosting staff may record payment.",
  },
  hostingPaymentCorrectionRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "HOSTING_PAYMENT_CORRECTION_REQUIRED",
    message: "Only Hosting staff may correct payment.",
  },
  claimApprovalRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "CLAIM_APPROVAL_REQUIRED",
    message: "Claim must be approved to record payment.",
  },
  fullTransferRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "FULL_TRANSFER_REQUIRED",
    message: "Transfer must equal the full approved EUR amount.",
  },
  claimPaidRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "CLAIM_PAID_REQUIRED",
    message: "Only a paid Claim can have its paid flag corrected.",
  },
  journeyDistanceOutsideBands: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "JOURNEY_DISTANCE_OUTSIDE_BANDS",
    message: "Journey distance must have exactly one frozen funding band.",
  },
  submissionIncomplete: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "CLAIM_SUBMISSION_INCOMPLETE",
    message: "Claim submission checklist is incomplete.",
  },
  partnerDocumentsRequired: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PARTNER_DOCUMENTS_REQUIRED",
    message: "Only the Partner Organization may manage Proof Documents.",
  },
  proofNotFound: {
    code: "NOT_FOUND",
    status: 404,
    reason: "PROOF_DOCUMENT_NOT_FOUND",
    message: "Proof Document not found in scope.",
  },
  proofSelectionRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PROOF_SELECTION_REQUIRED",
    message: "Select a file and Project Partnership.",
  },
  proofMediaUnsupported: {
    code: "UNSUPPORTED_MEDIA_TYPE",
    status: 415,
    reason: "PROOF_MEDIA_UNSUPPORTED",
    message: "Choose a PDF, JPEG, or PNG Proof Document.",
  },
  proofFileTooLarge: {
    code: "PAYLOAD_TOO_LARGE",
    status: 413,
    reason: "PROOF_FILE_TOO_LARGE",
    message: "Choose a Proof Document no larger than 10 MB.",
  },
  proofFileEmpty: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PROOF_FILE_EMPTY",
    message: "Choose a non-empty Proof Document.",
  },
  proofFileNameRequired: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PROOF_FILE_NAME_REQUIRED",
    message: "Choose a Proof Document with a file name.",
  },
  claimRequiredForProof: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "CLAIM_REQUIRED_FOR_PROOF",
    message: "Save an editable Claim before uploading a Proof Document.",
  },
  proofOriginDenied: {
    code: "FORBIDDEN",
    status: 403,
    reason: "PROOF_ORIGIN_DENIED",
    message: "Invalid upload origin.",
  },
  proofTransportTooLarge: {
    code: "PAYLOAD_TOO_LARGE",
    status: 413,
    reason: "PROOF_TRANSPORT_TOO_LARGE",
    message: "The upload request is too large.",
  },
  proofMultipartInvalid: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "PROOF_MULTIPART_INVALID",
    message: "Invalid multipart upload.",
  },
  proofUploadFailed: {
    code: "INTERNAL_SERVER_ERROR",
    status: 500,
    reason: "PROOF_UPLOAD_FAILED",
    message: "Upload failed. Please try again.",
  },
  proofDownloadFailed: {
    code: "INTERNAL_SERVER_ERROR",
    status: 500,
    reason: "PROOF_DOWNLOAD_FAILED",
    message: "Download failed. Please try again.",
  },
  badInput: {
    code: "BAD_REQUEST",
    status: 400,
    reason: "INVALID_INPUT",
    message:
      "We could not complete that request. Check your details and try again.",
  },
  accessDenied: {
    code: "FORBIDDEN",
    status: 403,
    reason: "ACCESS_DENIED",
    message: "You do not have permission to access this resource.",
  },
  notFound: {
    code: "NOT_FOUND",
    status: 404,
    reason: "RESOURCE_NOT_FOUND",
    message: "Resource not found in scope.",
  },
  conflict: {
    code: "CONFLICT",
    status: 409,
    reason: "STATE_CONFLICT",
    message:
      "The resource state conflicts with this request. Reload and try again.",
  },
  unprocessable: {
    code: "UNPROCESSABLE_CONTENT",
    status: 422,
    reason: "UNPROCESSABLE_REQUEST",
    message: "The request cannot be completed with the current details.",
  },
  rateLimited: {
    code: "TOO_MANY_REQUESTS",
    status: 429,
    reason: "RATE_LIMITED",
    message: "Too many requests were sent. Wait a moment and try again.",
  },
  unavailable: {
    code: "SERVICE_UNAVAILABLE",
    status: 503,
    reason: "SERVICE_UNAVAILABLE",
    message: "The service is temporarily unavailable. Try again later.",
  },
  internalFailure: {
    code: "INTERNAL_SERVER_ERROR",
    status: 500,
    reason: "INTERNAL_FAILURE",
    message: "Internal server error",
  },
} as const;

export const ErrorReasonSchema = z.enum([
  "SESSION_REQUIRED",
  "INVALID_CREDENTIALS",
  "ACTIVE_ORGANIZATION_REQUIRED",
  "ORGANIZATION_MEMBERSHIP_REQUIRED",
  "PARTICIPANT_PROFILE_REQUIRED",
  "PARTICIPANT_AGREEMENT_REQUIRED",
  "EMAIL_VERIFICATION_REQUIRED",
  "HOST_COORDINATION_REQUIRED",
  "PROJECT_NOT_FOUND",
  "PROJECT_PARTNERSHIP_NOT_FOUND",
  "ORGANIZATION_MANAGEMENT_REQUIRED",
  "PARTNER_COORDINATION_REQUIRED",
  "ELIGIBLE_COORDINATOR_REQUIRED",
  "INVALID_PROJECT_CURSOR",
  "PROJECT_READ_REQUIRED",
  "HOSTING_STAFF_REQUIRED",
  "HOSTING_SIDE_REQUIRED",
  "SELF_PARTNERSHIP",
  "PARTNER_ORGANIZATION_NOT_FOUND",
  "PARTNERSHIP_ALREADY_ASSIGNED",
  "PARTNERSHIP_INVARIANT",
  "PARTNERSHIP_REFERENCED",
  "PROJECT_ALREADY_COMPLETED",
  "SETUP_LINK_NOT_FOUND",
  "SETUP_LINK_WRONG_EMAIL",
  "SETUP_LINK_DISABLED",
  "SETUP_LINK_EXPIRED",
  "ORGANIZATION_OWNER_REQUIRED",
  "SETUP_LINK_USED",
  "STAFF_INVITATION_ROLE_TOO_HIGH",
  "STAFF_INVITATION_NOT_FOUND",
  "STAFF_INVITATION_WRONG_KIND",
  "STAFF_INVITATION_CLOSED",
  "STAFF_INVITATION_EXPIRED",
  "STAFF_INVITATION_WRONG_EMAIL",
  "INVALID_ORGANIZATION_ROLE",
  "PROJECT_COMPLETION_BLOCKED",
  "REGISTRATION_LINK_NOT_FOUND",
  "REGISTRATION_LINK_CLOSED",
  "PARTICIPANT_INVITATION_NOT_FOUND",
  "PARTICIPANT_INVITATION_WRONG_ACCOUNT",
  "PARTICIPANT_INVITATION_CLOSED",
  "PARTICIPANT_INVITATION_EXPIRED",
  "PARTICIPANT_ALREADY_PARTICIPATES",
  "PARTICIPANT_ALREADY_INVITED",
  "JOINED_OTHER_PARTNER",
  "MEMBERSHIP_CHANGED",
  "PARTICIPATION_IDENTITY_CONFLICT",
  "PARTICIPANT_INVITATION_ACCEPTED",
  "REGISTRATION_CLAIM_LOCKED",
  "PARTICIPANT_AGREEMENT_UNAVAILABLE",
  "PARTNER_CLAIM_EDIT_REQUIRED",
  "PAYOUT_SELECTION_LOCKED",
  "PARTNER_PAYOUT_SELECTION_REQUIRED",
  "PAYOUT_ACCOUNT_REQUIRED",
  "CLAIM_NOT_EDITABLE",
  "CLAIM_REQUIRED_FOR_COSTS",
  "PARTNER_COSTS_REQUIRED",
  "ALLOCATION_PARTICIPATION_REQUIRED",
  "COST_ENTRY_REQUIRED",
  "CLAIM_DOCUMENT_REFERENCES_REQUIRED",
  "PARTNER_JOURNEYS_REQUIRED",
  "JOURNEYS_LOCKED",
  "PARTICIPATION_SELECTION_REQUIRED",
  "JOURNEY_ALREADY_EXISTS",
  "CLAIM_REQUIRED_FOR_JOURNEY",
  "JOURNEY_SELECTION_REQUIRED",
  "PARTNER_ONBOARDING_PROGRESS_REQUIRED",
  "PARTNER_PARTICIPANT_SEARCH_REQUIRED",
  "PARTNER_PARTICIPATION_CREATE_REQUIRED",
  "PARTICIPATION_CREATE_LOCKED",
  "ELIGIBLE_PARTICIPANT_REQUIRED",
  "PARTICIPATION_DUPLICATE",
  "PARTICIPATION_REPRESENTATION_CONFLICT",
  "PARTNER_PARTICIPATION_UPDATE_REQUIRED",
  "PARTICIPATION_UPDATE_LOCKED",
  "PARTICIPATION_NOT_FOUND",
  "PARTNER_PARTICIPATION_REMOVE_REQUIRED",
  "PARTICIPATION_REMOVE_LOCKED",
  "PARTICIPATION_JOURNEY_OR_COST_REFERENCED",
  "PARTICIPATION_REFERENCED",
  "PARTNER_DUPLICATE_REVIEW_REQUIRED",
  "REVIEW_TASK_NOT_FOUND",
  "REVIEW_TASK_NOT_OPEN",
  "REVIEW_TASK_NOT_ASSIGNED",
  "REVIEW_TASK_ASSIGNEE_REQUIRED",
  "REVIEW_TASK_SURVIVOR_REQUIRED",
  "PARTNER_CLAIM_PREVIEW_REQUIRED",
  "PARTNER_CLAIM_SUBMIT_REQUIRED",
  "CLAIM_REQUIRED_FOR_SUBMISSION",
  "REVIEW_REASON_REQUIRED",
  "HOSTING_CLAIM_REVIEW_REQUIRED",
  "CLAIM_NOT_FOUND",
  "CLAIM_SUBMITTED_REQUIRED",
  "CLAIM_REJECTED_REQUIRED",
  "CLAIM_REVIEW_UNAVAILABLE",
  "HOSTING_PAYMENT_REQUIRED",
  "HOSTING_PAYMENT_CORRECTION_REQUIRED",
  "CLAIM_APPROVAL_REQUIRED",
  "FULL_TRANSFER_REQUIRED",
  "CLAIM_PAID_REQUIRED",
  "JOURNEY_DISTANCE_OUTSIDE_BANDS",
  "CLAIM_SUBMISSION_INCOMPLETE",
  "PARTNER_DOCUMENTS_REQUIRED",
  "PROOF_DOCUMENT_NOT_FOUND",
  "PROOF_SELECTION_REQUIRED",
  "PROOF_MEDIA_UNSUPPORTED",
  "PROOF_FILE_TOO_LARGE",
  "PROOF_FILE_EMPTY",
  "PROOF_FILE_NAME_REQUIRED",
  "CLAIM_REQUIRED_FOR_PROOF",
  "PROOF_ORIGIN_DENIED",
  "PROOF_TRANSPORT_TOO_LARGE",
  "PROOF_MULTIPART_INVALID",
  "PROOF_UPLOAD_FAILED",
  "PROOF_DOWNLOAD_FAILED",
  "INVALID_INPUT",
  "ACCESS_DENIED",
  "RESOURCE_NOT_FOUND",
  "STATE_CONFLICT",
  "UNPROCESSABLE_REQUEST",
  "RATE_LIMITED",
  "SERVICE_UNAVAILABLE",
  "INTERNAL_FAILURE",
]);
export const SafeErrorDataSchema = z
  .object({
    reason: ErrorReasonSchema,
    issues: z
      .array(
        z.object({ path: z.array(z.string()), message: z.string() }).strict(),
      )
      .optional(),
  })
  .strict();
export const errorDefinitions = {
  PAYLOAD_TOO_LARGE: { message: "Payload too large" },
  UNSUPPORTED_MEDIA_TYPE: { message: "Unsupported media type" },
  BAD_REQUEST: { message: "Bad request" },
  NOT_FOUND: { message: "Resource not found" },
  FORBIDDEN: { message: "Access forbidden" },
  UNAUTHORIZED: { message: "Unauthorized" },
  TOO_MANY_REQUESTS: { message: "Too many requests" },
  INTERNAL_SERVER_ERROR: { message: "Internal server error" },
  CONFLICT: { message: "Conflict" },
  UNPROCESSABLE_CONTENT: { message: "Unprocessable content" },
  SERVICE_UNAVAILABLE: { message: "Service unavailable" },
};

export function getSafeErrorSituation(error: {
  code: string;
  status: number;
  data?: unknown;
}) {
  const parsed = SafeErrorDataSchema.safeParse(error.data);
  if (!parsed.success) return undefined;
  return Object.values(situationCatalog).find(
    (s) =>
      s.reason === parsed.data.reason &&
      s.code === error.code &&
      s.status === error.status,
  );
}
