#!/usr/bin/env node
import crypto from "node:crypto";
import fs from "node:fs/promises";

async function getVersionFromPkg() {
  try {
    const pkg = JSON.parse(await fs.readFile("package.json", "utf8"));
    return pkg?.config?.scalarVersion;
  } catch (err) {
    // If package.json is simply missing (not running from repo root), provide clear guidance
    if (err && err.code === "ENOENT") {
      console.error(
        "package.json not found in the current directory (checked ",
        process.cwd(),
        ").",
      );
      console.error(
        "Set `config.scalarVersion` in package.json, pass a version to the script (e.g. `node scripts/generate-sri.js 1.25.0`), or set the SCALAR_VERSION environment variable.",
      );
      return undefined;
    }

    // For other errors (parse error, permission, etc.) provide actionable feedback
    console.error(
      "Error reading package.json to determine Scalar version:",
      err.message,
    );
    console.error(
      "Please ensure you're running this script from the repository root, that package.json is valid JSON, or pass the version as an argument (`node scripts/generate-sri.js 1.25.0`) or set SCALAR_VERSION.`",
    );
    process.exit(1);
  }
}

const version =
  process.argv[2] || process.env.SCALAR_VERSION || (await getVersionFromPkg());

if (!version) {
  console.error(
    "Scalar version is not set. Set `config.scalarVersion` in package.json, or pass a version to the script, or set SCALAR_VERSION env var.",
  );
  process.exit(1);
}

const url = `https://cdn.jsdelivr.net/npm/@scalar/api-reference@${version}/dist/browser/standalone.js`;

async function fetchAndHash() {
  console.log(`Fetching ${url}`);
  const res = await fetch(url, { headers: { "Accept-Encoding": "gzip, br" } });
  if (!res.ok) {
    throw new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
  }

  // arrayBuffer returns decompressed bytes in node fetch
  const buf = Buffer.from(await res.arrayBuffer());
  const hash = crypto.createHash("sha384").update(buf).digest("base64");
  const sri = `sha384-${hash}`;

  const outPath = "src/lib/orpc/scalar-sri.ts";
  const content = `// Generated by scripts/generate-sri.js. Do not edit by hand.
export const SCALAR_VERSION = ${JSON.stringify(version)};
export const SCALAR_URL = ${JSON.stringify(url)};
export const SCALAR_SRI = ${JSON.stringify(sri)};
`;

  await fs.writeFile(outPath, content, "utf8");
  console.log(`Wrote SRI to ${outPath}: ${sri}`);
}

fetchAndHash().catch((err) => {
  console.error("Failed to generate SRI:", err.message ?? err);
  console.error(
    "Hint: verify the Scalar version in package.json (config.scalarVersion), pass a version to the script, or check network connectivity and proxy settings.",
  );
  process.exit(1);
});
